// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/myAction.ts";
import * as $$$0 from "./loaders/myLoader.ts";
import * as $$$$$$0 from "./sections/mySection.tsx";

const manifest = {
  "loaders": {
    "breton-components/loaders/myLoader.ts": $$$0,
  },
  "sections": {
    "breton-components/sections/mySection.tsx": $$$$$$0,
  },
  "actions": {
    "breton-components/actions/myAction.ts": $$$$$$$$$0,
  },
  "name": "breton-components",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
